name: Keep Bot Alive

on:
  schedule:
    # Run every 5 hours to ensure continuous operation
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Keep repository active
      run: |
        # Update a timestamp file to keep the repo active
        echo "Last keep-alive: $(date -u)" > .github/keep-alive.txt
        
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Commit and push if there are changes
        if ! git diff --quiet; then
          git add .github/keep-alive.txt
          git commit -m "🤖 Keep-alive: $(date -u)"
          git push
          echo "✅ Keep-alive commit pushed"
        else
          echo "ℹ️ No changes to commit"
        fi
    
    - name: Trigger main bot workflow
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot.yml/dispatches \
          -d '{"ref":"${{ github.ref_name }}"}'
        echo "✅ Bot workflow triggered"